---
abstract: 'install a lightweight development environment'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Tiny
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features:
  Filesys:
    description: 'File system manipulation'
    recommends:
      Types::Path::Tiny: 0
    requires:
      Path::Tiny: 0
  HTTP:
    description: 'Web stuff'
    requires:
      HTTP::Tiny: 0
  JSON:
    description: 'JSON stuff'
    requires:
      JSON::PP: 0
  Objects:
    description: 'Framework for OO programming'
    recommends:
      Class::Method::Modifiers: 0
    requires:
      Class::Tiny: 0
      Class::Tiny::Antlers: 0
      Role::Tiny: 0
  Types:
    description: 'Type constraint framework'
    recommends:
      Types::Path::Tiny: 0
    requires:
      Type::Tiny: 0
  Util:
    description: 'General utilities'
    recommends:
      Config::Tiny: 0
    requires:
      Exporter::Tiny: 0
      Try::Tiny: 0
  YAML:
    description: 'YAML stuff'
    requires:
      YAML::Tiny: 0
provides:
  Task::Tiny:
    file: lib/Task/Tiny.pm
    version: 0.002
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Task-Tiny/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Task-Tiny
  homepage: https://metacpan.org/release/Task-Tiny
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-task-tiny
version: 0.002
